name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: '0 13 * * *' # Once a day at 1pm GMT / 7am MT (GMT-06:00) https://crontab.guru/#0_13_*_*_*

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    environment: Production
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      SPOTIFY_LOGIN: ${{ secrets.SPOTIFY_LOGIN }}
      SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      REFRESH_TOKEN_URL: ${{ secrets.REFRESH_TOKEN_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile 
      - run: yarn test
      - run: cp playlists.ci.json playlists.json
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn start