name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: '0 8 * * *' # Once a day at 8am https://crontab.guru/every-day-8am

jobs:
  update-playlists:
    runs-on: ubuntu-latest
    environment: Production
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      REFRESH_TOKEN_URL: ${{ secrets.REFRESH_TOKEN_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile 
      - run: yarn test
      - run: cp playlists.ci.json playlists.json
      - run: yarn start